version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

  zookeeper:
    image: zookeeper:3.9
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.5
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    restart: unless-stopped

  signoz:
    image: signoz/signoz:latest
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - KAFKA_BROKERS=kafka:9092
    ports:
      - "3301:3301"  # Web UI
      - "8080:8080"  # API
    volumes:
      - signoz_data:/var/lib/signoz
    depends_on:
      - clickhouse
      - kafka
    restart: unless-stopped

  otel-collector:
    image: signoz/signoz-otel-collector:0.88.16
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command:
      - "--config=/etc/otel-collector-config.yaml"
    depends_on:
      - clickhouse
      - kafka
    restart: unless-stopped

volumes:
  clickhouse_data:
  signoz_data:
