version: '3.8'

services:
  otel-collector:
    image: signoz/signoz-otel-collector:latest
    container_name: signoz-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "8889:8888" # Metrics endpoint for the collector itself
      - "9464:9464" # zpages endpoint for the collector
    restart: unless-stopped
    depends_on:
      - query-service

  query-service:
    image: signoz/query-service:latest
    container_name: signoz-query-service
    ports:
      - "8080:8080" # SigNoz UI and API
    environment:
      - TELEMETRY_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - CLICKHOUSE_HOSTS=clickhouse:9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - ENABLE_OPEN_TELEMETRY=true
    restart: unless-stopped
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: signoz-clickhouse
    ports:
      - "8123:8123" # ClickHouse HTTP interface
      - "9000:9000" # ClickHouse native interface
    volumes:
      - signoz-clickhouse-data:/var/lib/clickhouse
      - signoz-clickhouse-logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    restart: unless-stopped

volumes:
  signoz-clickhouse-data:
  signoz-clickhouse-logs:
